version: '3'
services:
  app: &app
    build: .
    command: revel run revel_docker_sample
    volumes:
      - ./:/go/src/revel_docker_sample
    depends_on:
      - db
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=revel
      - MYSQL_USER=revel
      - MYSQL_PASSWORD=secret
